### ISSUE TITLE
[Suggestion] New Logo icon for Unity Random Playlist

### ISSUE THREAD

**Issue by zularizal** [kretopi/UnityRandomPlaylist#1]
Hi, I want to contribute to this project, I want to design a logo, do you want it?

**Comment by kretopi** [comment]
Hi ok. Do you have any idea?

**Comment by zularizal** [comment]
I've created a logo, with different colors, what do you think? which one do you like?
![logo](https://user-images.githubusercontent.com/38547278/39389969-551102aa-4ab8-11e8-98cc-9de6d088412b.png)

**Comment by kretopi** [comment]
Nice, I would like to use the blue one, number 1.

**Comment by zularizal** [comment]
Okay, I've uploaded that logo to the drive, you can download it on this link https://drive.google.com/open?id=1ja6V_SRJKW43sA-zsr-_QRXQyhZQmBdi

and I sent a pull request to put the logo on the readme #3
